# Generated by Django 3.0 on 2021-07-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=300)),
                ('about_description', models.TextField()),
                ('about_image', models.ImageField(upload_to='uploads/about_us')),
                ('video_thumbnail', models.ImageField(upload_to='uploads/about_us')),
                ('video_url', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'About Us page content',
            },
        ),
    ]
