# Generated by Django 3.0 on 2021-07-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teambanner',
            options={'verbose_name_plural': 'Team Section '},
        ),
        migrations.AlterModelOptions(
            name='teams',
            options={},
        ),
    ]
