# Generated by Django 3.0 on 2021-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='user_profile',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
