# Generated by Django 3.0 on 2021-07-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='phone_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
