# Generated by Django 3.0 on 2021-07-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_aboutus_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='about_us_banner',
            field=models.ImageField(default=1, upload_to='uploads/about_us'),
            preserve_default=False,
        ),
    ]
