# Generated by Django 3.0 on 2021-07-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_post_title', models.CharField(help_text='Give a title', max_length=50)),
                ('footer_logo', models.ImageField(help_text='Upload Logo', upload_to='uploads/site_settings')),
                ('footer_short_about', models.TextField(help_text='Provide footer description and social as markup ')),
                ('footer_contact_details', models.TextField(help_text='Provide footer contact details as markup ')),
            ],
            options={
                'verbose_name_plural': 'Footer Settings',
            },
        ),
        migrations.CreateModel(
            name='TopBarSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Enter Phone number', max_length=20)),
                ('email', models.EmailField(help_text='Enter Email', max_length=254)),
                ('working_hours', models.CharField(help_text='Enter Working hour', max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Top Bar Settings',
            },
        ),
    ]
