# Generated by Django 3.0 on 2021-07-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_title', models.CharField(help_text='Give hero subtitle', max_length=150)),
                ('main_title', models.CharField(help_text='Giver hero main title', max_length=150)),
                ('background_image', models.ImageField(help_text='Upload background image', upload_to='uploads/hero')),
                ('left_animated_image', models.ImageField(help_text='Upload hero left image', upload_to='uploads/hero')),
                ('right_animated_image', models.ImageField(help_text='Upload hero right image', upload_to='uploads/hero')),
            ],
            options={
                'verbose_name_plural': 'Home Hero Slider Settings',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('service_no', models.CharField(max_length=10)),
                ('service_details', models.TextField(max_length=80)),
                ('service_icon_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Add Home Service',
            },
        ),
    ]
