# Generated by Django 3.0 on 2021-07-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=50)),
                ('service_no', models.CharField(max_length=10)),
                ('service_icons', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Add Home Service',
            },
        ),
    ]
