# Generated by Django 3.0 on 2021-07-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_services'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_icons',
            new_name='service_icon_name',
        ),
    ]
