# Generated by Django 3.0 on 2021-07-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210711_0743'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
