# Generated by Django 3.0 on 2021-07-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_services_service_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_details',
            field=models.TextField(max_length=80),
        ),
    ]
